### ISSUE TITLE
dirname() usage in DoctrineEntityManagerBuilder

### ISSUE THREAD

**Issue by ketanp77** [code-foundation/flow-config#8]
https://github.com/code-foundation/flow-config/blob/01c66f4004b72b64c69498d7b4e27b0c31ca7cb0/src/Config/DoctrineEntityManagerBuilder.php#L19

`dirname(__DIR__, 2)` can be used instead of `dirname(dirname(__DIR__))` to reduce number of calls.

**Comment by edward-murrell** [comment]
Fixed in PR #15, released in 0.2.0
